name: Push Tags

on: push

jobs:
  build:
    name: Push Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Push new tags
        run: ./.github/scripts/push-tags.sh
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_GITHUB_TOKEN }}"
